export * from './Home/HomePage.jsx'
export * from './Aboutus/Aboutus.jsx'
export * from './Contactus/Contactus.jsx'
export * from './Properties/Properties.jsx'
export * from './SingleView/SingleView.jsx'